---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04
- name: ubuntu-13.10
- name: ubuntu-12.04
- name: debian-7.2.0
- name: debian-6.0.8
- name: centos-6.5
- name: centos-5.10

suites:
- name: custom_port
  run_list:
  - recipe[minitest-handler]
  - recipe[sshd::default]
  attributes:
    sshd:
      sshd_config:
        Port: 1234

- name: conditional_block
  run_list:
  - recipe[minitest-handler]
  - recipe[sshd::default]
  attributes:
    sshd:
      sshd_config:
        Port: 1234
